package baseGame;
import java.awt.Color;

//This class represents a single peg. Codes in Mastermind consist of these pegs.
public class Peg {
	
	//The color of the peg, uses the java class "Color"
	private Color color;
	//The color of the peg as a string
	private String text;
	//The keypress that selects the peg (not currently implemented)
	private String key;
	// TODO add a bitmap image, or emoji here
	
	//autogenerated gets and sets
	public Color getColor() {
		return color;
	}
	public void setColor(Color color) {
		this.color = color;
	}
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public String getKey() {
		return key;
	}
	public void setKey(String key) {
		this.key = key;
	}
	

	//autogenerated constructor
	public Peg(Color color, String text, String key) {

		this.color = color;
		this.text = text;
		this.key = key;
	}
	
	public String toString(){
		return text;
	}
	
	
}
