import java.awt.Color;

public class Peg {
	
	
	private Color color;
	private String text;
	private String key;
	// add a bitmap image, or emoji here
	
	//autogenerated gets and sets
	public Color getColor() {
		return color;
	}
	public void setColor(Color color) {
		this.color = color;
	}
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public String getKey() {
		return key;
	}
	public void setKey(String key) {
		this.key = key;
	}
	

	//autogenerated constructor
	public Peg(Color color, String text, String key) {

		this.color = color;
		this.text = text;
		this.key = key;
	}
	
	public String toString(){
		return text;
	}
	
	
}
